create contributor phone
DTel-HQ/dtel pull request #258
Opened 2020-08-10 23:35 UTC by turret-dev

because contributors are epic 👍

2020-08-10 23:39 UTC, SunburntRock89 commented
There are 3 contributors. One doesn't use the bot at all. One of them is you. Perhaps you're trying to too your own horn slightly?

2020-08-10 23:40 UTC, turret-dev commented
but we have a redphone emote anyway so

2020-08-10 23:41 UTC, SunburntRock89 commented
You didn't deny it, and we don't need to use everything we have.

2020-08-10 23:42 UTC, turret-dev commented
i wouldn't even be able to use it because of my customer support so

2020-08-10 23:43 UTC, turret-dev commented
also according to (this)[https://github.com/DTel-HQ/dtel/graphs/contributors] we have 21 contributors including the dtel bosses and rexo

2020-08-10 23:44 UTC, SunburntRock89 commented
The people who have the role are the people who we care about here. If they don't have the role, they don't get the phone, and also probably don't care about the bot anymore

2020-08-11 09:03 UTC, Rexogamer commented
Sun did you fucking listen to Mitch's idea

Turret, I ❤️ this

2020-08-11 09:04 UTC, Rexogamer commented on Internals/callHandler.js
> +		if (msg.author.contributor) phone=config.callPhones.contributor;
Minor spacing error
```suggestion
		if (msg.author.contributor) phone = config.callPhones.contributor;
```

2020-08-11 09:14 UTC, Mitchell3514 commented
This wasn't exactly my idea. I thought the red phone was meant as a boss phone (which I also don't support, but don't mind either). 
Sun is definitely right, but also why not tbh.

2020-08-11 12:41 UTC, SunburntRock89 commented
Have you run this through ESLint? Also if you're gonna let this through, why don't you just go for the full shebang and make one for server boosters or something?

2020-08-11 19:06 UTC, turret-dev commented
boss phone would be like dark blue since their role color is blue

2020-08-11 19:21 UTC, SunburntRock89 commented on Structures/DTelUser.js
> +					donator: this.donator
agreed

2020-08-11 19:22 UTC, Rexogamer commented
ideas:
- pink one for boosters
- normal blue phone but with like yellow stripes for boss?
- orange for supervisor (required ASAP)

2020-08-11 19:22 UTC, SunburntRock89 commented
And just like that, you've eliminated your chances of getting a supervisor badge

2020-08-11 19:23 UTC, Rexogamer commented
they were just ideas, who burnt you

2020-08-11 19:34 UTC, austinhuang0131 commented
boosters should not get badges because we don't get any benefits

2020-08-11 21:45 UTC, turret-dev commented
this is just a commit about making a red phone for contributors, not fucking giving every single person a unique phone

2020-08-11 23:49 UTC, austinhuang0131 commented
reminder that this is a public repo

no profanity

2020-08-12 01:02 UTC, turret-dev commented
shit i broke the rules fuck

2020-08-12 15:55 UTC, turret-dev commented
mitchell, fyi the reason i removed the comma is because i added a contributor perm but then i was like "nah, contributor only commands aint comin" so then i removed it and didnt know that eslint gets picky with commas so i sowwy

2020-09-05 20:27 UTC, Rexogamer approved these changes
back on topic, this lgtm code wise (although maybe the red phone should be boss instead?)

2020-09-05 20:30 UTC, SunburntRock89 requested changes
Have you actually ran this and made sure it worked?

2020-09-05 20:32 UTC, Rexogamer commented
> Have you actually ran this and made sure it worked?

code wise this is basically the same as the other role phones, although whether it actually shows is another matter since CS is above it (out of scope but what if a user could have multiple phones showing)

2020-09-05 20:33 UTC, SunburntRock89 commented
> out of scope but what if a user could have multiple phones showing)
No, that'd just be cluttered

2020-09-05 22:33 UTC, Mitchell3514 commented
I'm not allowing us to lose our A+ on codacy, fix your code.

2020-09-05 22:43 UTC, Rexogamer commented
> I'm not allowing us to lose our A+ on codacy, fix your code.

all good now

2020-09-06 09:27 UTC, Mitchell3514 commented
This hound thing seems useless

2020-09-06 09:28 UTC, merged