feat: reduced >pay fee for vip users
DTel-HQ/dtel pull request #269
Opened 2020-11-01 15:56 UTC by Rexogamer

currently I've set it to a 15% fee (vs 27% for normal users). if this is okay I'll make the required changes to our advertising, if not let me know and I'll tweak it. until the rate is certain I'll keep this marked as a draft.

2020-11-01 18:17 UTC, turret-dev commented on Commands/Public/pay.js
> +			description: "Someone's sent you some credits. Here's your receipt.",
someone's?

2020-11-01 18:18 UTC, turret-dev requested changes
seems like a typo at line 126

2020-11-01 19:16 UTC, Mitchell3514 commented
Who exactly decided this would be done at all?

2020-11-01 20:31 UTC, Rexogamer commented
- it's more a suggestion rn
- I thought it would be a useful VIP benefit as the fee is kinda weird/high
- I submitted the PR to have the code there for reference/hopeful merger

2020-11-01 20:32 UTC, Rexogamer commented on Commands/Public/pay.js
> +			description: "Someone's sent you some credits. Here's your receipt.",
Yes...?
![73AE2DFE-944D-47F8-9E3E-D57ABD404D7D](https://user-images.githubusercontent.com/42586271/97814117-5eb1c680-1c81-11eb-838b-8e0717b2fd42.jpeg)

2020-11-01 20:39 UTC, Mitchell3514 commented
Yeah current fee is derived from old Discoin transfer penalty. I've wanted to lower it for a while. Could do like 10% and 5% or even 0% for vip.

2020-11-01 20:41 UTC, Rexogamer commented
suggestion
- 15 for normal
- 5/maybe 0 for vip

2020-11-06 20:07 UTC, Rexogamer commented
update for external followers/for future ref: we agreed on 15/5, at this point it's just docs

2020-11-06 20:08 UTC, Mitchell3514 approved these changes
Fixed myself

2020-11-06 20:08 UTC, Mitchell3514 commented
Wait for codacy then can mere

2020-11-06 20:10 UTC, Rexogamer commented on Commands/Public/pay.js
> +	let rate = fromAccount.vip ? config.vipTransferRate : config.normalTransferRate;
didn't know about <user>.donator but makes sense

2020-11-06 20:12 UTC, merged

2020-11-06 20:13 UTC, Rexogamer commented
Codacy seems to dislike the parentheses around your expression but 👍